version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=groupomaniaDB
    ports:
      - '5438:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/databaseSetup.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./database/mockData.sql:/docker-entrypoint-initdb.d/fill_tables.sql
